### ISSUE TITLE
FreeBSD: 0.15.0 fails to build

### ISSUE THREAD

**Issue by nunotexbsd** [rakshasa/libtorrent#284]
FreeBSD 15
Clang 19.1.5
libtorrent [port](https://www.freshports.org/net-p2p/libtorrent/)

Any clues?
Full log bellow from poudriere packager.

Thanks

```
--- throttle.lo ---
In file included from throttle.cc:43:
In file included from ./../net/throttle_internal.h:41:
../../rak/priority_queue_default.h:56:7: warning: '~priority_item' has a non-throwing exception specification but can still throw [-Wexceptions]
   56 |       throw torrent::internal_error("priority_item::~priority_item() called on a queued item.");
      |       ^
../../rak/priority_queue_default.h:54:3: note: destructor has a implicit non-throwing exception specification
   54 |   ~priority_item() {
      |   ^
--- rate.lo ---
In file included from rate.cc:39:
In file included from ./../globals.h:5:
../../rak/priority_queue_default.h:56:7: warning: '~priority_item' has a non-throwing exception specification but can still throw [-Wexceptions]
   56 |       throw torrent::internal_error("priority_item::~priority_item() called on a queued item.");
      |       ^
../../rak/priority_queue_default.h:54:3: note: destructor has a implicit non-throwing exception specification
   54 |   ~priority_item() {
      |   ^
--- poll_kqueue.lo ---
poll_kqueue.cc:284:41: error: no member named 'equal' in namespace 'rak'
  284 |                                    rak::equal(event, rak::mem_ref(&kevent::udata))) - m_changes;
      |                                    ~~~~~^
poll_kqueue.cc:284:59: error: no member named 'mem_ref' in namespace 'rak'
  284 |                                    rak::equal(event, rak::mem_ref(&kevent::udata))) - m_changes;
      |                                                      ~~~~~^
--- poll_select.lo ---
poll_select.cc:127:5: warning: '~PollSelect' has a non-throwing exception specification but can still throw [-Wexceptions]
  127 |     throw internal_error("PollSelect::~PollSelect() called but the sets are not empty");
      |     ^
poll_select.cc:120:13: note: destructor has a implicit non-throwing exception specification
--- poll_kqueue.lo ---
poll_kqueue.cc:310:41: error: no member named 'equal' in namespace 'rak'
  310 |                                    rak::equal(event, rak::mem_ref(&kevent::udata))) - m_changes;
      |                                    ~~~~~^
poll_kqueue.cc:310:59: error: no member named 'mem_ref' in namespace 'rak'
  310 |                                    rak::equal(event, rak::mem_ref(&kevent::udata))) - m_changes;
      |                                                      ~~~~~^
4 errors generated.
*** [poll_kqueue.lo] Error code 1
```
Full log: 
[libtorrent-0.15.0.log](https://github.com/user-attachments/files/18255460/libtorrent-0.15.0.log)

**Comment by stickz** [comment]
@kannibalox This is a regression from #274.

**Comment by nunotexbsd** [comment]
Build fixed.
Thanks for quick support.

**Comment by rakshasa** [comment]
Fixed.
