### ISSUE TITLE
FreeBSD: missing header #include <sys/socket.h> causes build to fail

### ISSUE THREAD

**Issue by nunotexbsd** [rakshasa/libtorrent#841]
FreeBSD amd64
clang version 21.1.8

```
...
--- runtime/runtime.lo ---
libtool: compile:  c++ -std=c++20 -DHAVE_CONFIG_H -I. -I../.. -I. -I./.. -I../.. -isystem /usr/local/include -I/usr/local/include -pthread -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -DNDEBUG -Wall -fvisibility=hidden -I /usr/include -MT runtime/runtime.lo -MD -MP -MF runtime/.deps/runtime.Tpo -c runtime/runtime.cc  -fPIC -DPIC -o runtime/.libs/runtime.o
--- system/system.lo ---
system/system.cc:131:8: error: use of undeclared identifier 'AF_UNSPEC'
--- runtime/socket_manager.lo ---
depbase=`echo runtime/socket_manager.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`; /bin/sh ../../libtool  --tag=CXX    --mode=compile c++ -std=c++20 -DHAVE_CONFIG_H  -I. -I../..  -I. -I./.. -I../.. -isystem /usr/local/include   -I/usr/local/include  -pthread  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -isystem /usr/local/include  -DNDEBUG -Wall -fvisibility=hidden -I /usr/include -MT runtime/socket_manager.lo -MD -MP -MF $depbase.Tpo -c -o runtime/socket_manager.lo runtime/socket_manager.cc && mv -f $depbase.Tpo $depbase.Plo
--- system/system.lo ---
  131 |   case AF_UNSPEC:
      |        ^~~~~~~~~
system/system.cc:133:8: error: use of undeclared identifier 'AF_INET'
  133 |   case AF_INET:
      |        ^~~~~~~
system/system.cc:135:8: error: use of undeclared identifier 'AF_INET6'
  135 |   case AF_INET6:
      |        ^~~~~~~~
system/system.cc:137:8: error: use of undeclared identifier 'AF_UNIX'
  137 |   case AF_UNIX:
      |        ^~~~~~~
4 errors generated.
*** [system/system.lo] Error code 1

make[3]: stopped making "all" in /wrkdirs/usr/ports/net-p2p/libtorrent/work/libtorrent-0.16.18/src/torrent
--- runtime/socket_manager.lo ---
libtool: compile:  c++ -std=c++20 -DHAVE_CONFIG_H -I. -I../.. -I. -I./.. -I../.. -isystem /usr/local/include -I/usr/local/include -pthread -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -DNDEBUG -Wall -fvisibility=hidden -I /usr/include -MT runtime/socket_manager.lo -MD -MP -MF runtime/.deps/socket_manager.Tpo -c runtime/socket_manager.cc  -fPIC -DPIC -o runtime/.libs/socket_manager.o
make[3]: 1 error
```

Fixed locally with:
```diff
--- src/torrent/system/system.cc.orig	2026-07-17 09:47:03 UTC
+++ src/torrent/system/system.cc
@@ -8,6 +8,7 @@
 #include "torrent/system/callbacks.h"
 #include "torrent/system/thread.h"
 #include "torrent/system/types.h"
+#include <sys/socket.h>
 
 namespace torrent::system {
 

```

Thanks

**Comment by gdt** [comment]
The bug was introduced in https://github.com/rakshasa/libtorrent/commit/4d9627bcadf8df4f8d68b97351ea3c348909d5db

**Comment by rakshasa** [comment]
`fix/various-release-issues`

**Comment by rakshasa** [comment]
Merged.
